# Generated by Django 4.0 on 2023-01-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
