# Generated by Django 4.0 on 2023-01-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='static/photos')),
                ('price', models.FloatField()),
            ],
        ),
    ]
