# Generated by Django 4.0 on 2023-01-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, upload_to='video/course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(upload_to='photos/courses'),
        ),
    ]
