# Generated by Django 4.0 on 2023-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='idCourse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
