# Generated by Django 4.0 on 2023-01-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_photo_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
