# Generated by Django 4.0 on 2023-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_photo_uploader_delete_blog_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default/anonymous-user.png', upload_to='photos/courses'),
        ),
    ]
