# Generated by Django 4.0 on 2023-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='idCourse',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
