# Generated by Django 4.0 on 2023-01-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_learner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
