# Generated by Django 4.0 on 2023-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/users/'),
        ),
    ]
