# Generated by Django 4.0 on 2023-01-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_learner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
