# Generated by Django 4.0 on 2023-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_category_alter_learner_phone_course_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(null=True),
        ),
    ]
