# Generated by Django 4.0 on 2023-02-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_video_video_alter_course_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
