# Generated by Django 4.0 on 2024-01-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(default=12345678, max_length=255),
            preserve_default=False,
        ),
    ]
