# Generated by Django 4.0 on 2024-01-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='coins',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
