# Generated by Django 4.0 on 2024-02-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_learner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learner',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
