# Generated by Django 4.0 on 2024-02-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='instagram',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='tiktok',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
