# Generated by Django 4.0 on 2024-02-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_learner_instagram_alter_learner_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
