# Generated by Django 4.0 on 2024-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_learner_instagram_alter_learner_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
